# Generated by Django 5.1.3 on 2024-11-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_permission_role_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_setup_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
